# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master #main

pr:
  branches:
    include:
      - master #main

pool:
  vmImage: ubuntu-latest

variables: 
- group: 'SnykSecrets'

steps:
- task: UseNode@1
  inputs:
    version: '18.x'

- script: npm install
  displayName: 'Install Dependencies'

- script: npm run build
  displayName: 'Build Application'

#SCA test
- script: snyk test --file=package.json --severity-threshold=low
  displayName: 'Snyk SCA Test'

#SAST Test
- script: snyk code test --severity-threshold=low
  displayName: 'Snyk SAST Test'
