# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master #main

pr:
  branches:
    include:
      - master #main

pool:
  vmImage: ubuntu-latest

variables:
  system.debug: true #Debug logging

steps:
- task: UseNode@1
  inputs:
    version: '18.x'
  displayName: 'Setup Node.js'

- script: npm install
  displayName: 'Install Dependencies'

# - script: npm run build
#   displayName: 'Build Application'

# - script: snyk test -d
#   displayName: 'Run snyk security tests'
  

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'snyk'
    testType: 'app'
    monitorWhen: 'always'
    failOnIssues: true
    projectName: 'juice-shop'
    organization: 'NSSF Group'
    

